path_to_cacm = "data/CACM/"
path_cacm_all = path_to_cacm + "cacm.all"
path_cacm_common_words = path_to_cacm + "common_words"
path_cacm_qrels = path_to_cacm + "qrels.text"
path_cacm_query = path_to_cacm + "query.text"
term_termid_file_name = "term_termid.txt"
termid_postings_file_name = "termid_postings.txt"
